<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Scaling.AI.Agents.With.Aspire.AppHost.ServiceDefaults\Scaling.AI.Agents.With.Aspire.AppHost.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
